name = "DirichletDiffusion"
uuid = "982e8bbf-e5c7-4ea7-a34d-76b67b1e00c4"
version = "0.1.0"
authors = ["dan-sprague <d.a.sprague@outlook.com>"]

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Bijectors = "76274a88-744f-5084-9051-94815aaf08c4"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ADTypes = "1.20.0"
Bijectors = "0.15.14"
CairoMakie = "0.15.7"
ChainRulesCore = "1.26.0"
Colors = "0.13.1"
Distances = "0.10.12"
Distributions = "0.25.122"
FillArrays = "1.15.0"
LinearAlgebra = "1.12.0"
Mooncake = "0.4.182"
StaticArrays = "1.9.15"
StatsFuns = "1.5.2"
Turing = "0.42.0"
Zygote = "0.7.10"
