name = "DirichletDiffusion"
uuid = "982e8bbf-e5c7-4ea7-a34d-76b67b1e00c4"
version = "0.1.0"
authors = ["dan-sprague <d.a.sprague@outlook.com>"]

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1.26.0"
Distances = "0.10.12"
Distributions = "0.25.122"
FillArrays = "1.15.0"
LinearAlgebra = "1.12.0"
Mooncake = "0.4.182"
StaticArrays = "1.9.15"
Turing = "0.42.0"
Zygote = "0.7.10"
